### ISSUE TITLE
ContainerNotFound Exception on Action Deployment

### ISSUE THREAD

**Issue by webdog** [actions/azure#2]
:wave:

When deploying the example code in the README, the Action finishes deploying, but fails in the Azure UI.

`webapp create --resource-group $RESOURCE_GROUP --plan $APP_SERVICE_PLAN --name $WEBAPP_NAME --deployment-container-image-name $CONTAINER_IMAGE_NAME`

It appears that in the UI, when this command is executed on a webapp that doesn't previously exist, the `--deployment-container-image-name` argument predisposes itself to Docker Hub. Thus, the Docker Image is not found as the action does not publish to Docker Hub.

```
2018-10-29 15:11:57.144 INFO  - Starting container for site
2018-10-29 15:11:57.146 INFO  - docker run -d -p 20839:80 --name webdog-app_0 -e WEBSITES_ENABLE_APP_SERVICE_STORAGE=false -e WEBSITE_SITE_NAME=webdog-app -e WEBSITE_AUTH_ENABLED=False -e PORT=80 -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_INSTANCE_ID=48474d08fdd542f5da22046275c9c9dc84eaeeadd698ad306840751e7e1990b0 webdog/actions-django-azure:master  

2018-10-29 15:11:57.147 INFO  - Logging is not enabled for this container.
Please use https://aka.ms/linux-diagnostics to enable logging to see container logs here.
2018-10-29 15:11:57.178 ERROR - Container create failed for webdog-app_0 with System.AggregateException, One or more errors occurred.
InnerException: Docker.DotNet.DockerContainerNotFoundException, Docker API responded with status code=NotFound, response={"message":"No such image: webdog/actions-django-azure:master"}
```

**Comment by webdog** [comment]
According to `az webapp create` this is intended behavior:

```
--deployment-container-image-name -i : Linux only. Container image name from Docker Hub, e.g.
                                           publisher/image-name:tag.
```

I will attempt to deploy again without this command line argument in the action

**Comment by webdog** [comment]
After attempting to re-run, it appears that my docker image **must** be published to DockerHub. The action/Azure is not honoring my Dockerfile that lives in my repo.

Any workaround you might suggest?

**Comment by nickvanw** [comment]
@webdog: I believe this is expected behavior - this action is intended to be used in tandem with other actions inside of the workflow file to build and publish an image, and then deploy it. 

I believe we should update the README to indicate this, cc @swinton.

**Comment by nickvanw** [comment]
@webdog: That depends on whether the container being deployed is public or private - if it's public, no additional credentials would be needed.

I don't believe that `az webapp create` has a configuration option for setting the registry username and password for a private registry, I believe one would have to use `webapp config` (ref: https://docs.microsoft.com/en-us/cli/azure/webapp/config/container?view=azure-cli-latest). 

If you want to investigate how that functions, I wouldn't be opposed.

**Comment by swinton** [comment]
@webdog, apologies for the confusion here.

The example is based off [this tutorial](https://docs.microsoft.com/en-us/azure/app-service/containers/tutorial-custom-docker-image), and does assume [the pre-existence of a Docker image than can be deployed](https://docs.microsoft.com/en-us/azure/app-service/containers/tutorial-custom-docker-image#push-the-docker-image-to-docker-hub). It picks up from the tutorial at [the Create a web app step](https://docs.microsoft.com/en-us/azure/app-service/containers/tutorial-custom-docker-image#create-a-web-app).

> I believe we should update the README to indicate this

:+1:
